version: '3.8'

services:
  app:
    build: .
    container_name: alfa-leetcode-api-docker
    ports:
      - '3000:3000'
    restart: always
    environment:
      - WDS_SOCKET_HOST=127.0.0.1 
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - LIMIT_SKIP_TOKEN=aahftab
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    # command: npm run dev
    command: node dist/index.js
